### ISSUE TITLE
Problem with images

### ISSUE THREAD

**Issue by djbuch** [retyui/prestashop-1.7-webpack-3-hot-module-replacement#1]
Hello,

I've a little problem with the image see here
https://stackoverflow.com/questions/48542375/webpack-hmr-static-files-404ing

If you have any idea.

Regards,
And thanks for the work

**Comment by retyui** [comment]
@djbuch Hellow David!
I did not encounter such a problem :(
Maybe I can help you if you make a test repository!

**Comment by djbuch** [comment]
OK,

I'll try.
Is it possible that I have this error because I don't use local server but are proxying distant (my install is to difficult to have locally) ?
I don't have the problem on the CSS files, only on other static files.

Regards,

**Comment by retyui** [comment]
@djbuch I update all repo to the elegant appearance. and probably your problem was because of publicPath)

**Comment by djbuch** [comment]
@retyui I tried to update to your new version, but it seems that HMR not starts. I have browserSync working, but no change is pushed, and in the browser console I don't have any HMR logs.

**Comment by retyui** [comment]
@djbuch  I can not help you if you do not create a test repository

**Comment by djbuch** [comment]
Hi,
here is my code : https://github.com/djbuch/prestashop-1.7-webpack-3-hot-module-replacement/

**Comment by retyui** [comment]
@djbuch 
here http://boutiquenanou.code-utopia.com/ installed theme `webp_mercerie`
But in the file `themes/classic-demo-hot/_dev/_webpack/util.js`
you set  
```js
themeFolderName: 'classic-hot-demo', // folder name your theme
```
You understand that this is a very silly?

**Comment by djbuch** [comment]
That is not really the problem, I changed this in the file to have the same name as the repos theme. But locally I had webp_mercerie.

The thing is that randomly the HMR starts on the browser (I see logs in the console) and randomly it doesn’t. I was not able to determine the reason

**Comment by djbuch** [comment]
I found how to get HMR running, but it's a bit od...

While watch is running I have to make a change and have the watch rebuilding the code, then when I open the browser HMR is working.

If I open the browser before any change has been done, HMR is not running and future changes will not be seen.

If you have an idea.

Regards,

**Comment by retyui** [comment]
@djbuch 
if you do not understand how to proksirovat remote prestashop.
Use the local copy of  prestashop + docker

**Comment by djbuch** [comment]
It’s not a problem of proxy.
Local cannot be used since we are differents  developers working on the
same project (back end / front end)

**Comment by retyui** [comment]
@djbuch I recommend reading about using git in a command, and setting up deploy on a production
Ваша проблема заключается в том что

**Comment by retyui** [comment]
@djbuch  Well, if you think that the problem is not proxy ...
can you decorate this code:
https://github.com/webpack/webpack-dev-middleware/blob/master/lib/middleware.js#L26-L30

**Comment by djbuch** [comment]
We are using Git and Buddy to deploy in dev and production.

But when backend dev is doing changes on the database, and the frontend
needs to have access to theses it's more complicated
