### ISSUE TITLE
Does not generate a style file theme.css in developer mode

### ISSUE THREAD

**Issue by alexmixaylov** [retyui/prestashop-1.7-webpack-3-hot-module-replacement#2]
thank you very much!!!
I am trying to create webpack config, but I have always faleen

I cloned and turned on your theme successfully
when I am trying to build script - all right
if it is development mode - it is not errors, but the style file theme.css have not generated 

Debian *64
Node v8.10.0
Yarn  v1.5.1

**Comment by retyui** [comment]
quote from [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware#webpack-dev-middleware)

> Some of the benefits of using this middleware include:
> **No files are written to disk, rather it handles files in memory**
> If files changed in watch mode, the middleware delays requests until compiling has completed.
> Supports hot module reload (HMR).

**Comment by alexmixaylov** [comment]
Thanks
I had bug this https://github.com/PrestaShop/PrestaShop/pull/8865
so i had not seen the result
Now it all right, but [HMR] bundle rebuilt in 5534ms
How are you thinking  can it rebuilt faster?

**Comment by retyui** [comment]
@alexmixaylov 
yes, I know how rebuilt it faster!
Every time if you change scss, webpack recompile file `theme.scss` and all his imported children files again.

Thus, each separate `scss` file will become separate with the module.
That will allow us, when changing any of them, not to re-compile the whole file in the `theme.scss`.
It is important that the contents of files(`theme.scss, theme.scss.js`) coincide!

I recommend that you make the following changes:

1)
```js
// webpack.config.js
module.exports = {
    entry: {
        theme: [
            "swiper/dist/css/swiper.css",
            DEV ? "./js/theme.scss.js" : "./scss/theme.scss",
            "./js/theme.js"
        ],
    }
};
````
2) file `theme.scss.js`
```js
import "../scss/lib/_global.scss";
import "../scss/lib/_icons.scss";
import "../scss/lib/_grid.scss";
import "../scss/lib/_video.scss";
import "../scss/lib/_btn.scss";
import "../scss/lib/_c-section.scss";

import "../scss/page/_header.scss";
import "../scss/page/_footer.scss";

import "../scss/page/_breadcrumbs.scss";
import "../scss/page/_instagram.scss";
import "../scss/page/_newsletter.scss";
import "../scss/page/_cms.scss";
import "../scss/page/_top-categories.scss";
import "../scss/page/_c-category-view.scss";
import "../scss/page/_c-interactive-catalog.scss";
import "../scss/page/_minicart.scss";
import "../scss/page/_quick-view.scss";

import "./product/scss/product.scss";
```
2.2) File 
```scss
@import "lib/global";
@import "lib/icons";
@import "lib/grid";
@import "lib/video";
@import "lib/btn";
@import "lib/c-section";

@import "page/header";
@import "page/breadcrumbs";
@import "page/instagram";
@import "page/newsletter";
@import "page/cms";
@import "page/footer";
@import "page/top-categories";
@import "page/c-category-view";
@import "page/c-interactive-catalog";
@import "page/minicart";
@import "page/quick-view";

@import "../js/product/scss/product";
```

3) if file (example `_header.scss`) uses global variables , we need to export these variables from the "config\variables" file!
```scss
@import "../config";
// ...
```

**Comment by alexmixaylov** [comment]
Thank you very much
I'll be trying it
